name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "7 23 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "alecqie@163.com"
          git config --local user.name "xj75q"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "自动点绿"
          git push
